name: sncf_lookfor
description: "Application de recherche d'objet perdu SNCF"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lookfor-logo.png
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf

flutter_native_splash:
  color: "#0C131F"  # Correction de la couleur
  image: assets/images/sncf-logo.png  # Utilisation du logo SNCF
  android: true
  ios: true
  web: true
